# songs = { vardaan,
#           Yalgaar,
#           Cold Hours,
#           Life Goes On,
#           No Need, 
#           Fairytail, 
#           Believer, 
#           Bones, 
#           Pasoori, 
#           Excuses,
#           Jaadugar,
#           RAASHAH, 
#           Bt Ho Gayi, 
#           Cheap Thrills}